### ISSUE TITLE
Geofencing with push notification

### ISSUE THREAD

**Issue by CVarisco** [radshag/PhoneGap-Geofencing#46]
Hi,

i have tried to develop an application with Phonegap (for Android).
My app and the plugin work when it is open, but when i close the app and i enter in a region my application crash from the background.

This is my js code:

``` javascript
var GOOGLE_PROJECT_ID = "<myID>";
var PUSHAPPS_APP_TOKEN = "<myToken>";

function registerDevice() {
    PushNotification.registerDevice(GOOGLE_PROJECT_ID, PUSHAPPS_APP_TOKEN, function (pushToken) {
        alert('registerDevice, push token' + pushToken);
    }, function (error) {
        alert(error);
    });

    document.removeEventListener('pushapps.message-received');
    document.addEventListener('pushapps.message-received', function(event) {
        var notification = event.notification;

        var devicePlatform = device.platform;
        if (devicePlatform === "iOS") {

            alert("message-received, Message: " + notification.aps.alert + " , D: " + notification.D);
        } else {
            alert("message-received, Message: " + notification.Message + " , Title: " + notification.Title + " , D: " + notification.D);
        }
    });
}

function sendNumberTag() {
    var d = 3;
    var iden = 2;

    PushNotification.setTags([{
                              identifier: iden,
                              value: d
                              }], function () {
                                 alert("Your tag was successfully added");
                             }, function (message) {
                                 alert("ERROR: " + message);
                             });
}

var app = {

    initialize: function() {
        this.bindEvents();
    },

    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },

    onDeviceReady: function() {
        app.receivedEvent('deviceready');
    },

    processRegionMonitorCallback: function(result) {
        var callbacktype = result.callbacktype;
        alert(callbacktype);
        if (callbacktype == "initmonitor") {

        } else if (callbacktype == "locationupdate") {

            var fid = result.regionId;

            var new_timestamp = result.new_timestamp;
            var new_speed = result.new_speed;
            var new_course = result.new_course;
            var new_verticalAccuracy = result.new_verticalAccuracy;
            var new_horizontalAccuracy = result.new_horizontalAccuracy;
            var new_altitude = result.new_altitude;
            var new_latitude = result.new_latitude;
            var new_longitude = result.new_longitude;

            var old_timestamp = result.old_timestamp;
            var old_speed = result.old_speed;
            var old_course = result.old_course;
            var old_verticalAccuracy = result.old_verticalAccuracy;
            var old_horizontalAccuracy = result.old_horizontalAccuracy;
            var old_altitude = result.old_altitude;
            var old_latitude = result.old_latitude;
            var old_longitude = result.old_longitude;

        } else if (callbacktype == "monitorremoved") {

        } else if (callbacktype == "monitorfail") {

        } else if (callbacktype == "monitorstart") {

        } else if (callbacktype == "enter") {

            alert("YOU ENTER IN");
            sendNumberTag();

        } else if (callbacktype == "exit") {

        }
    },


    // Update DOM on a Received Event
    receivedEvent: function() {
         window.plugins.DGGeofencing.initCallbackForRegionMonitoring(new Array(), app.processRegionMonitorCallback, function(error) {
             console.log("init error");
         });

         var params = ["1", "45.572994", "9.192647", "10"];
         window.plugins.DGGeofencing.startMonitoringRegion(params, function(result) { console.log('watching');}, function(error) {
             console.log("failed to add region");
         });

         registerDevice();

    }
};

app.initialize();
```

Why doesn't work ? Thanks :)

**Comment by zeusstl** [comment]
Here is the logcat I get for this issue. Can any java experts get anything of value from this?
(For privacy, replaced the actual app name with [appname] in the output.)

I/ActivityManager(  548): Start proc com.[appname] for broadcast com.[appname]/com.phonegap.geofencing.ProximityReceiver: pid=6280 uid=10063 gids={50063, 9997, 3003, 1028, 1015} abi=armeabi-v7a
I/art     ( 6280): Late-enabling -Xcheck:jni
D/Geofencing( 6280): received proximity alert for region 1
I/ActivityManager(  548): Killing 3441:com.google.android.apps.docs.editors.docs/u0a137 (adj 15): empty #17
D/AndroidRuntime( 6280): Shutting down VM
E/AndroidRuntime( 6280): FATAL EXCEPTION: main
E/AndroidRuntime( 6280): Process: com.[appname], PID: 6280
E/AndroidRuntime( 6280): java.lang.RuntimeException: Unable to start receiver com.phonegap.geofencing.ProximityReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.phonegap.geofencing.DGGeofencing.fireRegionChangedEvent(android.content.Intent)' on a null object reference
E/AndroidRuntime( 6280): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2586)
E/AndroidRuntime( 6280): 	at android.app.ActivityThread.access$1700(ActivityThread.java:144)
E/AndroidRuntime( 6280): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
E/AndroidRuntime( 6280): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6280): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6280): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime( 6280): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6280): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 6280): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime( 6280): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/AndroidRuntime( 6280): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.phonegap.geofencing.DGGeofencing.fireRegionChangedEvent(android.content.Intent)' on a null object reference
E/AndroidRuntime( 6280): 	at com.phonegap.geofencing.ProximityReceiver.onReceive(ProximityReceiver.java:18)
E/AndroidRuntime( 6280): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2579)
E/AndroidRuntime( 6280): 	... 9 more

**Comment by zeusstl** [comment]
Does anyone have any suggestions on this?

**Comment by zeusstl** [comment]
Related and helpful:
https://github.com/chenjishi/android_location_demo/issues/2
